import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Átila's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head>
        <link rel="icon" type="image/svg+xml" href="./public/macbook.png" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
